version: '3.9'

services:
  mysql_db:
    image: mysql:8.3
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: pychecker
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 700s
      start_interval: 10s
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./entrypoint.sh"]
    container_name: next_web
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: rebuild
          path: src/
          target: .
        - action: sync
          path: public/
          target: app/public/
        - action: sync
          path: __tests__/
          target: app/__tests__/
        - action: sync
          path: jest.config.js
          target: app/jest.config.js
        - action: sync
          path: jest.setup.js
          target: app/jest.setup.js
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
    driver: local